{% set name = "sharrow" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sharrow-{{ version }}.tar.gz
  sha256: 2f267b4c80ebf9594d28f380ac5fcd9d85e83c04eacdfd56caba2612b8dfe072

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7,!=3.8
    - setuptools-scm
  run:
    - dask-core
    - filelock
    - networkx
    - numba >=0.53
    - numexpr
    - numpy >=1.19
    - pandas >=1.2
    - pyarrow >=3.0.0
    - python >=3.9
    - xarray >=0.20.0
    - sparse

test:
  imports:
    - sharrow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ActivitySim/sharrow
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A compiler for ActivitySim-style utility specification files

extra:
  recipe-maintainers:
    - jpn--
