{% set name = "sharrow" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sharrow-{{ version }}.tar.gz
  sha256: d8411f5785e487f680068738b89a96ca952f41c265e4bf002cd05698ed0fe37f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - dask-core
    - filelock
    - networkx
    - numba >=0.53
    - numexpr
    - numpy >=1.19
    - pandas >=1.2
    - pyarrow >=3.0.0
    - python >=3.9
    - xarray >=0.20.0

test:
  imports:
    - sharrow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ActivitySim/sharrow
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A compiler for ActivitySim-style utility specification files

extra:
  recipe-maintainers:
    - jpn--
